# Generated by Django 5.2.7 on 2025-12-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PISTOLA', 'Pistola'), ('RIFLE', 'Rifle'), ('ESPINGARDA', 'Espingarda')], max_length=20)),
                ('numero_serie', models.CharField(max_length=50, unique=True)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
    ]
